export const TIMEZONES = [
  { label: "Auto-Detected (System Local)", value: "" },
  { label: "Saudi Arabia (AST, UTC+3)", value: "Asia/Riyadh" },
  { label: "UAE / Dubai (GST, UTC+4)", value: "Asia/Dubai" },
  { label: "Pakistan (PKT, UTC+5)", value: "Asia/Karachi" },
  { label: "Qatar (AST, UTC+3)", value: "Asia/Qatar" },
  { label: "Kuwait (AST, UTC+3)", value: "Asia/Kuwait" },
  { label: "Bahrain (AST, UTC+3)", value: "Asia/Bahrain" },
  { label: "Oman (GST, UTC+4)", value: "Asia/Muscat" },
  { label: "United Kingdom / London (GMT/BST)", value: "Europe/London" },
  { label: "US / New York (EST/EDT)", value: "America/New_York" },
  { label: "US / Chicago (CST/CDT)", value: "America/Chicago" },
  { label: "US / Los Angeles (PST/PDT)", value: "America/Los_Angeles" },
  { label: "Canada / Toronto (EST/EDT)", value: "America/Toronto" },
  { label: "France / Paris (CET/CEST)", value: "Europe/Paris" },
  { label: "Germany / Berlin (CET/CEST)", value: "Europe/Berlin" },
  { label: "Australia / Sydney (AEST/AEDT)", value: "Australia/Sydney" },
  { label: "Singapore / Malaysia (SGT, UTC+8)", value: "Asia/Singapore" },
  { label: "India (IST, UTC+5:30)", value: "Asia/Kolkata" },
];
