
export const AppView = {
  PUBLIC_HOME: 'PUBLIC_HOME',
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  CLASSROOM: 'CLASSROOM',
  FEED: 'FEED',
  MARKETPLACE: 'MARKETPLACE',
  TEACHER_PROFILE: 'TEACHER_PROFILE',
  INTERNAL_STUDENT_PROFILE: 'INTERNAL_STUDENT_PROFILE',
  INSTRUCTORS_DIRECTORY: 'INSTRUCTORS_DIRECTORY',
};

